[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Specific routes mapped first
[[redirects]]
  from = "/about/"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/guides/"
  to = "/guides/index.html"
  status = 200

[[redirects]]
  from = "/disclaimer"
  to = "/disclaimer/index.html"
  status = 200

[[redirects]]
  from = "/downloads/"
  to = "/downloads/index.html"
  status = 200

# Fallback for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
